# Generated by Django 3.2.15 on 2022-09-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsM', '0002_subscribedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
