# Generated by Django 3.2.15 on 2022-10-09 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migrations to the DB"""
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventsM', '0003_auto_20220930_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField
                    (null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
